### ISSUE TITLE
Mouse hiding.

### ISSUE THREAD

**Issue by ghost** [pelya/xserver-xsdl#33] opened 2015-02-07 17:35 UTC
Is it possible to hide one of cursors (there are two) while using hardware mouse?
I have one mouse from chrooted linux (ubuntu, linux deploy), and one from android (hardware mouse). 
Thank's for advance.

**Comment by ghost** [comment] 2015-02-07 17:40
Also, this server don't correctly detect my resolution (I think it's because of my bottom bar for touch button's (I have no hardware buttons on tablet)), and I have at top black bar where I can't move mouse and anything.

**Comment by ghost** [comment] 2015-02-07 17:49
Normally it detect correct resolution, but I switch from it to Linux Deploy for running Linux and back to this app, and after it, it's mess. Of course native and correct resolution selected. Screenshot:
![screenshot_2015-02-07-18-46-46](https://cloud.githubusercontent.com/assets/5048555/6093066/d2991270-aef9-11e4-9229-b20ad028d595.png)

**Comment by pelya** [comment] 2015-02-08 16:28
You will need to hide mouse cursor in Linux settings, an app cannot hide
Android mouse cursor.

I've got reports of that black bar bug ,but I cannot reproduce it on Nexus
7. What device are you using? You can kind of fix that by clicking "Change
device config" - "Video" and disabling immersive mode.

On Sat, Feb 7, 2015 at 7:49 PM, Patryk Szczepański <notifications@github.com

**Comment by ghost** [comment] 2015-02-09 14:38
Samsung Galaxy Tab 2 10.1 WiFi without 3G (GT-P5110) running on Cyanogenmod 11. Maybe it's CM issue, I don't know.

**Comment by ghost** [comment] 2015-02-09 17:07
If I can help, and you have debug version, so send me it, and I will send you log's (or if it's possible without debug version, let me know). If it's even possible to log this bug, and if this can provide any useful information...

**Comment by DavideRossi** [comment] 2015-02-12 23:51
I have the same issue on a Lenovo Yoga Tablet 2 (native res in 1920x1200). The worst part of it is that the "real" android pointer (I'm using a bluetooth mouse) is some 100 pixels to the top of the screen with respect to the X pointer.
If I can be of any help to debug this out just let me know.

**Comment by pelya** [comment] 2015-02-13 00:07
I'll have more free time to debug this issue in two weeks. For now I can
only propose to install older release from
http://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/

**Comment by DavideRossi** [comment] 2015-02-13 08:53
I forgot to mention that the X server that comes with your "Debian noroot" app from the play store works just fine. I'll try some older version of the X server in the next days.

**Comment by pelya** [comment] 2015-02-23 16:16
I've finally got some free time, and reproduced the issue on simulator with Android 4.4, I hope I'll fix it this week.

**Comment by pelya** [comment] 2015-02-23 18:18
Black bar bug sohuld be fixed in 1.11.25, please test and reopen the bug if it does not work for you.

**Closed as completed by pelya** 2015-02-23 18:18 UTC

**Comment by downwa** [comment] 2016-03-15 21:13
Running XSDL on RemixOS I not only have two mouse pointers, but the Android one is somewhat below the XSDL one on the screen.  This means moving to the LXDE menu requires moving my Android pointer below the XSDL window.  But once outside the window I cannot click on the LXDE menu, of course.  So basically, a portion of the XSDL screen is unreachable by a mouse click.

(This is in addition to the annoyance of having two visible cursors).

Turning off the Linux cursor is not an option since it is the one that is correctly positioned relative to Linux.  In other words, a mouse click is registered at the Linux pointer location even when the Android pointer location is different.

I was able to get the pointers synchronized at one point by dragging to different corners of the screen, but they quickly get out of sync.

**Comment by downwa** [comment] 2016-03-15 21:14
Is there a setting (or could one be added) such that the pointers would always track together (maybe emulate a touch pad instead of a mouse?)

**Comment by pelya** [comment] 2016-03-15 21:32
Once XSDL detects that you're using a mouse, it switches to the absolute
coordinates. By default finger input has relative coordinates. But maybe
RemixOS simulates finger with mouse.

Try selecting different option in 'Change device config' - 'Mouse emulation'

**Comment by downwa** [comment] 2016-03-17 18:03
I tried changing settings but it was already showing unchecked on relative coordinates.  But if it detects finger input and switches to relative after startup, I'm unable to see or change the setting at that point.

**Comment by pelya** [comment] 2016-03-17 18:06
Select 'Mouse emulation mode' - 'Large (tablets)' from the same menu, it
will force absolute coordinates even for finger input.

**Comment by downwa** [comment] 2016-03-17 19:58
Okay, I've tried "Display size for mouse emulation": Large (tablets).  
Under "advanced features" nothing is checked.  But I still get two 
out-of-sync mouse cursors.

In summary, I'm running XSDL on RemixOS.  I'm running LXDE under Ubuntu 
as my Linux environment.  The whole thing is running on a Dell Vostro 
laptop, with a physical USB mouse plugged in.

Let me know if there is any information to help debugging this issue.

Warren
