### ISSUE TITLE
 X server failed to launch

### ISSUE THREAD

**Issue by Malcom3D** [pelya/xserver-xsdl#32] opened 2015-01-11 12:36 UTC
Hi Pelya,
thank you for the effort on this app. I've some problem starting the xserver.
I own a xt925 phone with CM10.1.3.
After the count down screen, the Xserver won't start; it print:

"Error: X server failed to launch
This may happen because of SELinux or because installation was corrupted"

SElinux isn't compiled. I've try to clean cache data and reinstall the app, but I think something is wrong in my setup.
Looking at the logcat I can see some error about swap interval and keyboard init:

I/ActivityManager(  719): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=x.org.server/.MainActivity} from pid 1058
D/dalvikvm(  719): GC_FOR_ALLOC freed 1653K, 26% free 15396K/20704K, paused 138ms, total 145ms
I/dalvikvm-heap(  719): Grow heap (frag case) to 18.379MB for 1048592-byte allocation
I/ActivityManager(  719): Start proc x.org.server for activity x.org.server/.MainActivity: pid=7344 uid=10071 gids={50071, 3003, 1015, 1028}
I/SDL     ( 7344): libSDL: Creating startup screen
W/ActivityManager(  719): Unable to start service Intent { cmp=x.org.server/.DummyService } U=0: not found
I/SDL     ( 7344): libSDL: onWindowFocusChanged: true - sending onPause/onResume
I/ActivityManager(  719): Displayed x.org.server/.MainActivity: +352ms
I/SDL     ( 7344): libSDL: Loading libraries
I/SDL     ( 7344): libSDL: loaded GLESv2 lib
I/SDL     ( 7344): libSDL: loading lib /data/data/x.org.server/files/../lib/libsdl_native_helpers.so
D/dalvikvm( 7344): Trying to load lib /data/data/x.org.server/files/../lib/libsdl_native_helpers.so 0x40ea2358
D/dalvikvm( 7344): Added shared lib /data/data/x.org.server/files/../lib/libsdl_native_helpers.so 0x40ea2358
D/dalvikvm( 7344): No JNI_OnLoad found in /data/data/x.org.server/files/../lib/libsdl_native_helpers.so 0x40ea2358, skipping init
I/SDL     ( 7344): libSDL: loading lib /data/data/x.org.server/files/../lib/libsdl-1.2.so
D/dalvikvm( 7344): Trying to load lib /data/data/x.org.server/files/../lib/libsdl-1.2.so 0x40ea2358
D/dalvikvm( 7344): Added shared lib /data/data/x.org.server/files/../lib/libsdl-1.2.so 0x40ea2358
I/SDL     ( 7344): libSDL: loading lib /data/data/x.org.server/files/../lib/libsdl_ttf.so
D/dalvikvm( 7344): Trying to load lib /data/data/x.org.server/files/../lib/libsdl_ttf.so 0x40ea2358
D/dalvikvm( 7344): Added shared lib /data/data/x.org.server/files/../lib/libsdl_ttf.so 0x40ea2358
D/dalvikvm( 7344): No JNI_OnLoad found in /data/data/x.org.server/files/../lib/libsdl_ttf.so 0x40ea2358, skipping init
I/SDL     ( 7344): libSDL: Trying to extract binaries from assets binaries-armeabi-v7a.zip
I/SDL     ( 7344): File '/data/data/x.org.server/files/usr/bin/xli' exists and passed CRC check - not overwriting it
I/SDL     ( 7344): File '/data/data/x.org.server/files/usr/bin/xhost' exists and passed CRC check - not overwriting it
I/SDL     ( 7344): File '/data/data/x.org.server/files/usr/bin/xsel' exists and passed CRC check - not overwriting it
I/SDL     ( 7344): File '/data/data/x.org.server/files/usr/bin/xkbcomp' exists and passed CRC check - not overwriting it
I/SDL     ( 7344): File '/data/data/x.org.server/files/busybox' exists and passed CRC check - not overwriting it
I/SDL     ( 7344): Extracting binaries finished
I/SDL     ( 7344): libSDL: Loading settings
I/SDL     ( 7344): libSDL: Settings.Load(): enter
I/SDL     ( 7344): android.os.Build.MODEL: XT925
I/SDL     ( 7344): libSDL: Settings.Load(): loaded settings successfully
I/SDL     ( 7344): libSDL: old cfg version 11121, our version 11121
I/InputReader(  719): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  719): Device reconfigured: id=1, name='melfas-ts', size 720x1280, orientation 1, mode 1, display id 0
I/InputReader(  719): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  719): Device reconfigured: id=1, name='melfas-ts', size 720x1280, orientation 1, mode 1, display id 0
I/ActivityManager(  719): Config changes=480 {1.0 222mcc1mnc it_IT ldltr sw360dp w640dp h335dp 320dpi nrml long land finger -keyb/v/h -nav/h s.14 themeResource=null}
I/SDL     ( 7344): libSDL: loading lib /data/data/x.org.server/files/../lib/libapplication.so
D/dalvikvm( 7344): Trying to load lib /data/data/x.org.server/files/../lib/libapplication.so 0x40ea2358
D/dalvikvm( 7344): Added shared lib /data/data/x.org.server/files/../lib/libapplication.so 0x40ea2358
D/dalvikvm( 7344): No JNI_OnLoad found in /data/data/x.org.server/files/../lib/libapplication.so 0x40ea2358, skipping init
I/SDL     ( 7344): libSDL: loading lib /data/data/x.org.server/files/../lib/libsdl_main.so
D/dalvikvm( 7344): Trying to load lib /data/data/x.org.server/files/../lib/libsdl_main.so 0x40ea2358
D/dalvikvm( 7344): Added shared lib /data/data/x.org.server/files/../lib/libsdl_main.so 0x40ea2358
I/SDL     ( 7344): libSDL: 3000-msec timeout in startup screen
D/dalvikvm(  934): GC_FOR_ALLOC freed 654K, 61% free 9862K/24940K, paused 21ms, total 21ms
I/dalvikvm-heap(  934): Grow heap (frag case) to 18.088MB for 6410576-byte allocation
D/dalvikvm(  934): GC_CONCURRENT freed 5K, 36% free 16117K/24940K, paused 1ms+10ms, total 37ms
D/dalvikvm(  934): GC_FOR_ALLOC freed 1K, 36% free 16117K/24940K, paused 18ms, total 18ms
I/dalvikvm-heap(  934): Grow heap (frag case) to 24.626MB for 6860816-byte allocation
D/dalvikvm(  934): GC_CONCURRENT freed 0K, 28% free 22817K/31644K, paused 2ms+4ms, total 38ms
D/dalvikvm(  719): GC_EXPLICIT freed 924K, 26% free 16158K/21732K, paused 3ms+13ms, total 133ms
I/SDL     ( 7344): libSDL: Timeout reached in startup screen, process with downloader
I/SDL     ( 7344): libSDL: Starting data downloader
I/SDL     ( 7344): libSDL: Starting downloader
I/SDL     ( 7344): libSDL: Initializing video and SDL application
D/SDL     ( 7344): libSDL: DemoRenderer.onWindowResize(): 1280x720
D/libEGL  ( 7344): loaded /system/lib/egl/libEGL_adreno200.so
D/libEGL  ( 7344): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
D/libEGL  ( 7344): loaded /system/lib/egl/libGLESv2_adreno200.so
I/Adreno200-EGL( 7344): <qeglDrvAPI_eglInitialize:269>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB_VANILLA.04.02.02.60.051_msm8960_JB_VANILLA_CL2997615_release_AU (CL2997615)
I/Adreno200-EGL( 7344): Build Date: 04/11/13 Thu
I/Adreno200-EGL( 7344): Local Branch:
I/Adreno200-EGL( 7344): Remote Branch: quic/mako_jb_mr1
I/Adreno200-EGL( 7344): Local Patches: NONE
I/Adreno200-EGL( 7344): Reconstruct Branch: AU_LINUX_ANDROID_JB_VANILLA.04.02.02.60.051 +  NOTHING
I/SDL     ( 7344): libSDL: DemoRenderer.onSurfaceCreated(): paused false mFirstTimeStart true
I/SDL     ( 7344): libSDL: DemoRenderer.onSurfaceChanged(): paused false mFirstTimeStart false w 1280 h 720
I/libSDL  ( 7344): Physical screen resolution is 1280x720
I/SDL     ( 7344): libSDL: setting envvar LANGUAGE to 'it_IT'
D/SDL     ( 7344): libSDL: Is running on OUYA: false
I/SDL     ( 7344): libSDL: starting gyroscope
I/libSDL  ( 7344): Changing curdir to "/storage/emulated/0/Android/data/x.org.server/files"
I/libSDL  ( 7344): Calling SDL_main("XSDL")
I/libSDL  ( 7344): param 0 = "XSDL"
I/XSDL    ( 7344): Actual video resolution 1280/103x720/57
I/XSDL    ( 7344): User u0_a71 ID 10071
I/XSDL    ( 7344): Current video mode: 1280 720
I/libSDL  ( 7344): SDL_SetVideoMode(): application requested mode 480x320 OpenGL 0 HW 0 BPP 16
E/libSDL  ( 7344): ERROR: Setting the swap interval is not supported
E/libSDL  ( 7344): ERROR: Getting the swap interval is not supported
E/libSDL  ( 7344): ERROR: GL_GetAttribute not supported
I/libSDL  ( 7344): ANDROID_GL_GetProcAddress("glGetString"): 0x40035cc0
D/BHD     (  311): Got a battery uevent,log details
I/XSDL    ( 7344): TCP port 6000 already used, trying next one: Address already in use
I/XSDL    ( 7344): TCP port 6001 already used, trying next one: Address already in use
I/XSDL    ( 7344): TCP port 6002 already used, trying next one: Address already in use
I/XSDL    ( 7344): TCP port 6003 already used, trying next one: Address already in use
I/XSDL    ( 7344): 2 network interfaces found
I/XSDL    ( 7344): interface: lo address: 127.0.0.1
I/XSDL    ( 7344): interface: wlan0 address: 192.168.1.129
I/XSDL    ( 7344): XSDL video resolution 1280/147x720/81x16, args:
I/XSDL    ( 7344): > XSDL
I/XSDL    ( 7344): > :4
I/XSDL    ( 7344): > -nolock
I/XSDL    ( 7344): > -noreset
I/XSDL    ( 7344): > -fp
I/XSDL    ( 7344): > /data/data/x.org.server/files/img/usr/share/fonts/X11/misc,/data/data/x.org.server/files/img/usr/share/fonts/X11/Type1,/data/data/x.org.server/files/img/usr/share/fonts/X11/100dpi,/data/data/x.org.server/files/img/usr/share/fonts/X11/75dpi,/data/data/x.org.server/files/img/usr/share/fonts/X11/cyrillic
I/XSDL    ( 7344): > -screen
I/XSDL    ( 7344): > 1280/147x720/81x16
I/XSDL    ( 7344): > -exec
I/XSDL    ( 7344): > /data/data/x.org.server/files/usr/bin/xhost + ; /data/data/x.org.server/files/usr/bin/xli -onroot -center /storage/emulated/0/Android/data/x.org.server/files/background.bmp
I/XSDL    ( 7344): XSDL chdir to: /data/data/x.org.server/files
I/XSDL    ( 7344): InitConnectionLimits: MaxClients = 255
I/XSDL    ( 7344): InitCard: (null)
I/XSDL    ( 7344): Calling SDL_Init()
I/XSDL    ( 7344): _XSERVTrans
I/XSDL    ( 7344): mkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
I/XSDL    ( 7344): _XSERVTrans
I/XSDL    ( 7344): mkdir: ERROR: Cannot create /tmp/.X11-unix
I/XSDL    ( 7344): _XSERVTrans
I/XSDL    ( 7344): SocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
I/XSDL    ( 7344): _XSERVTrans
I/XSDL    ( 7344): MakeAllCOTSServerListeners: failed to create listener for unix
I/XSDL    ( 7344): sdlScreenInit
I/XSDL    ( 7344): Attempting for 1280x720/16bpp mode
I/libSDL  ( 7344): SDL_SetVideoMode(): application requested mode 1280x720 OpenGL 0 HW 0 BPP 16
E/libSDL  ( 7344): ERROR: Setting the swap interval is not supported
E/libSDL  ( 7344): ERROR: Getting the swap interval is not supported
E/libSDL  ( 7344): ERROR: GL_GetAttribute not supported
I/libSDL  ( 7344): ANDROID_GL_GetProcAddress("glGetString"): 0x40035cc0
I/XSDL    ( 7344): Set 1280x720/16bpp mode
I/XSDL    ( 7344): sdlMapFramebuffer: shadow 0
I/XSDL    ( 7344): sdlRandRInit
I/XSDL    ( 7344): InitOutput()
I/XSDL    ( 7344): sdlCreateRes
I/XSDL    ( 7344): [dix] Could not init font path element /data/data/x.org.server/files/img/usr/share/fonts/X11/misc, removing from list!
I/XSDL    ( 7344): [dix] Could not init font path element /data/data/x.org.server/files/img/usr/share/fonts/X11/Type1, removing from list!
I/XSDL    ( 7344): [dix] Could not init font path element /data/data/x.org.server/files/img/usr/share/fonts/X11/100dpi, removing from list!
I/XSDL    ( 7344): [dix] Could not init font path element /data/data/x.org.server/files/img/usr/share/fonts/X11/75dpi, removing from list!
I/XSDL    ( 7344): [dix] Could not init font path element /data/data/x.org.server/files/img/usr/share/fonts/X11/cyrillic, removing from list!
I/XSDL    ( 7344): [xkb] XkbDDXCompileKeymapByNames executes: /data/data/x.org.server/files/usr/bin/xkbcomp -I/data/data/x.org.server/files/usr/share/X11/xkb -w 1 "-R/data/data/x.org.server/files/usr/share/X11/xkb" -xkm - -em1 xkbcomp: -emp --- -eml ======= /data/data/x.org.server/files/server-4.xkm
I/XSDL    ( 7344): [xkb] XkbDDXCompileKeymapByNames compiling keymap:
I/XSDL    ( 7344): (EE) Error compiling keymap (server-4)
I/XSDL    ( 7344): (EE) XKB: Couldn't compile keymap
I/XSDL    ( 7344): (EE) XKB: Failed to load keymap. Loading default keymap instead.
I/XSDL    ( 7344): [xkb] XkbDDXCompileKeymapByNames executes: /data/data/x.org.server/files/usr/bin/xkbcomp -I/data/data/x.org.server/files/usr/share/X11/xkb -w 1 "-R/data/data/x.org.server/files/usr/share/X11/xkb" -xkm - -em1 xkbcomp: -emp --- -eml ======= /data/data/x.org.server/files/server-4.xkm
I/XSDL    ( 7344): [xkb] XkbDDXCompileKeymapByNames compiling keymap:
I/XSDL    ( 7344): (EE) Error compiling keymap (server-4)
I/XSDL    ( 7344): (EE) XKB: Couldn't compile keymap
I/XSDL    ( 7344): XKB: Failed to compile keymap
I/XSDL    ( 7344): Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
I/XSDL    ( 7344):
I/XSDL    ( 7344): Fatal server error:
I/XSDL    ( 7344): Failed to activate core devices.
I/XSDL    ( 7344):
I/XSDL    ( 7344): (dix) removing device 2
I/XSDL    ( 7344): (dix) removing device 3
I/XSDL    ( 7344): Current video mode: 1280 720
I/libSDL  ( 7344): SDL_SetVideoMode(): application requested mode 480x320 OpenGL 0 HW 0 BPP 16
E/libSDL  ( 7344): ERROR: Setting the swap interval is not supported
E/libSDL  ( 7344): ERROR: Getting the swap interval is not supported
E/libSDL  ( 7344): ERROR: GL_GetAttribute not supported
I/libSDL  ( 7344): ANDROID_GL_GetProcAddress("glGetString"): 0x40035cc0

I hope you can help me. Thank you very much!

**Comment by pelya** [comment] 2015-01-11 19:40
Seems like statically linked xkbcomp executable fails to run. I've already
seen reports of similar errors, although not often. Blame Lollipop for
that, because previously I've used dynamically-linked executable, which
worked everywhere except Lollipop.

I'll just compile xkbcomp as a shared library, and link it with main XSDL
app.

I think I'll publish a new version in two weeks or so.

**Comment by Malcom3D** [comment] 2015-01-11 20:59
Thank you very much for your answer.
Do you remember the last version with xkbcomp dynamically-linked?
I would like to make a try before your next release.

**Comment by pelya** [comment] 2015-01-11 21:07
Look here for a build which was released before Lollipop:
http://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/

**Comment by Malcom3D** [comment] 2015-01-11 23:17
You are right on the problem.
I've tried version 1.11.19 and it worked perfectly.
Thank you again for your support.

**Comment by pelya** [comment] 2015-01-11 23:54
Hey do not close it, I did not fix it yet for new version.

**Comment by pelya** [comment] 2015-01-13 20:15
I've published an update 1.11.22 to Google Play, which contains two
versions of xkbcomp, for Lollipop and pre-Lollipop devices, could you
please test it on your phone?

**Comment by Malcom3D** [comment] 2015-01-13 20:36
Hi Pelya,
i'm sorry but it doesn't work.
I get the same error as the previous version (after clean the cache and set the configuration to default).
If you like I can test the next build before publishing it on Google Play.

Thank you again for your effort.

**Comment by pelya** [comment] 2015-01-15 15:38
Are you sure that version 1.11.19 works for you? It also contains
statically-linked executables, identical to those in version 1.11.21 you've
tried to use initially. The last version with dynamically-linked
executables is 1.11.18. And both versions of executables run fine inside
emulator and on ancient HTC Evo with Android 2.3, so I cannot reproduce the
problem.

**Comment by Malcom3D** [comment] 2015-01-15 18:21
Hi,
yes, the version is 1.11.19.
I've chosen your last build before the official release of lollipop.
I'm really sorry because at this time i haven't time to understand why it work. But xkbcomp build the keymap and my debian chroot with lxde run smooth on this android 4.2.2 (CyanogenMod 10.1.3)
When i'm back from this business travel i can try to build and fix the source until it work for me. For now I can only test your releases, and rollback to the one that work.
Let me know if I can do something to help you understand what happen.

Thank you.

**Comment by pelya** [comment] 2015-01-15 20:26
I've reproduced the issue on that Android 2.3 device, apparently running
xkbcomp from inside the app is somehow different than running it from adb
shell.

**Comment by pelya** [comment] 2015-01-16 19:26
I've fixed app not running on Android 2.3 device, could you please check
version 1.11.23 from Google Play?

**Comment by Malcom3D** [comment] 2015-01-16 23:27
Hi,
now it work like a charm!!
Thank you very much!!
Where can I make a little donation for your work?

**Comment by pelya** [comment] 2015-01-17 00:23
I don't accept donations at the moment.

**Closed as completed by pelya** 2015-01-17 00:23 UTC

**Comment by depore** [comment] 2015-06-07 07:33
hey im having the same kind of problem, but im using the Samsung Galaxy S6

**Comment by pelya** [comment] 2015-06-07 14:12
Can you please capture ADB logs when the app is starting?

**Comment by screen317** [comment] 2015-06-24 17:59
Hey I'm encountering the same error on my Note 4. How do I get ADB logs for you? Tried current version and 1.11.19 with no luck.

**Comment by pelya** [comment] 2015-06-24 19:38
It's a different error with Note 4, caused by it's new 64-bit architecture,
but I've fixed it just today. Could you please check an update 1.11.30 from
Google Play?
