### ISSUE TITLE
broken keymaps if using other than "us"

### ISSUE THREAD

**Issue by fleixi** [pelya/xserver-xsdl#56] opened 2016-01-17 16:57 UTC
i have plugged an usbkeyboard on my device with a german keylayout. if i start xsdl and a desktopenverment (mate) i could use the us keylayout but the shift keys mapped by 6 and 7 are the same (&). if i switch to german keylayout i get some more missing keys like small "ö,ä,ü" and 6 and 7 are mapped both to "/". big "Ö,Ä,Ü" are working in german layout.

**Comment by gfkpth** [comment] 2016-03-13 01:32
Hi there, I have run into essentially the same issue, see also here: https://github.com/pelya/commandergenius/issues/40

What I have been doing so far is switching the keyboard layout inside my linux chroot - I have been using the xfce keyboard switcher applet, but I suspect setxkbmap from the terminal should work. The problem is that this seems to work ONLY if you set up your chroot with wheezy. On jessie or testing or any other distro I've tried (at least if you're using Linux Deploy for installation as I do), the xserver crashes once I switch to anything but US. My current workaround is to setup my system with wheezy, apt-pinning it and then adding jessie and testing for my texlive packages and some other stuff I need newer than wheezy. This way, you can switch your keyboard layout in Linux independently of the setting in Android - in fact, you need to leave the Android keyboard setting on US for this method because otherwise your input gets mixed up again (probably because Android sends keycodes assuming German layout, xsdl xserver transforms for Linux but Linux transforms them again.
I haven't figured out what is crashing the Xserver, but once I upgraded too many packages and ended up with the same problem, so be careful when upgrading.
It's probably not the most elegant, and I'd love to be able to run plain jessie or testing, but at the moment it's a working solution if you have trouble switching your keyboard layout in Android.

**Comment by gfkpth** [comment] 2016-03-13 02:40
Ok, now I feel a bit stupid for not having tried this earlier. It seems that changing the keyboard layout with setxkbmap works fine, even on Debian testing!
It seems that this should be a viable workaround now. At the same time, it seems that there are some gaps in the implementation of how the Xserver translates Android keyinput to Linux keyinput, at least for the German layout (apart from Shift+6 and Shift+7 this also concerns most/all combinations with AltGr, which blocks input of keys like { or [ in the German layout.

**Comment by Nixola** [comment] 2016-12-20 08:21
I would like to report that, being an Italian user, I would like to be able to use the Italian physical keyboard layout in Android while being able to have a functioning layout with XSDL; I've tried four layouts in Linux with the Italian one set (us, gb, de, it) and all of them are broken.

**Comment by pelya** [comment] 2020-02-26 21:39
Should be fixed in 1.20.47

**Closed as completed by pelya** 2020-02-26 21:39 UTC
