### ISSUE TITLE
Screen display and touch detection incorrect when in immersive mode

### ISSUE THREAD

**Issue by fernandofig** [pelya/xserver-xsdl#36] opened 2015-02-16 22:10 UTC
Hi there. I've been using XServer-SDL for awhile together with [Linux Deploy](https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy), to run a Debian Chroot'ed on my Android, with a GUI (currently XFCE). FYI, I'm running this on a LG G Pad 8.3 with CyanogenMod 11. This has worked fine for a long time, but since version 1.11.23 (released about a month ago) it hasn't been working correctly: when in immersive mode (the LG G Pad doesn't have dedicated home/back/menu buttons btw, it uses android's soft keys instead), the display of the GUI is offset vertically by about the same vertical size of the navigation bar and so is touch detection on the GUI environment - meaning, a touch at some point of the screen registers a bit below where the touch occured on the GUI. For example, if I want to activate the XFCE menu, instead of touching directly on the button, I should touch a little over at the top of it, where it is supposed to be if the display wasn't offset. When I bring up the navigation bar the display is no longer offset and reacts correctly, but that's less than ideal since then I lose a little chunk of vertical space. A picture speaks more than a thousand words, so here it goes.

![screenshot_2015-02-16-18-52-46](https://cloud.githubusercontent.com/assets/1110864/6219985/b137e6fe-b617-11e4-9e92-a8d97e4e04a5.png)

I'm now using version 1.11.22 (which works correctly) until this can be resolved.

Thanks!

**Comment by pelya** [comment] 2015-02-16 23:14
Other users also reported that bug, I hope I'll fix it in two weeks, but I moght need your help, because I cannot reproduce it myself.

**Comment by fernandofig** [comment] 2015-02-16 23:23
No problem - just let me know what you need. I'll be away on vacation for the remainder of this week (starting tomorrow, until Sunday), and I'm not yet sure if the place where I'm going to be will have any 3G coverage, so you might need to wait a bit for a reply if you're going to tackle this during this period, but other than that, I'll be glad to help.

**Comment by pelya** [comment] 2015-02-23 18:18
Should be fixed in 1.11.25, please test and reopen the bug if it does not work.

**Closed as completed by pelya** 2015-02-23 18:18 UTC
